#!/bin/sh

exec 0</dev/null
exec 1>/dev/null
exec 2>/dev/null

(
pgctl light_10p
sleep 2
pgctl light_20p
sleep 2
pgctl light_40p
sleep 2
pgctl light_60p
sleep 2
pgctl light_on
sleep 2
pgctl mains_on
) &
