#!/bin/sh

exec 0</dev/null
exec 1>/dev/null
exec 2>/dev/null

(
if [ "$(cat /tmp/.pgctl_light)" != off ]; then
	pgctl fadedown
fi
pgctl s4_p1_off
pgctl s4_p2_off
pgctl s2_p2_on
pgctl s2_p5_off
pgctl s1_p2_off
pgctl s1_p4_off
pgctl s3_all_off
pgctl mains_off
) &
