#!/bin/sh

exec 0</dev/null
exec 1>/dev/null
exec 2>/dev/null

(
sleep 5
pgctl mains_off
sleep 5
pgctl light_60p
sleep 5
pgctl light_40p
sleep 5
pgctl light_20p
sleep 5
pgctl light_10p
sleep 5
pgctl light_off
) &
